Repository etalab/udata-gouvfr, pull requests merged in 2018-02, with the labels that each got.

#264 New Crowdin translations
  udata_gouvfr/theme/translations/es/LC_MESSAGES/gouvfr.po
  udata_gouvfr/theme/translations/fr/LC_MESSAGES/gouvfr.po
  udata_gouvfr/translations/es/LC_MESSAGES/udata-gouvfr.po
  udata_gouvfr/translations/fr/LC_MESSAGES/udata-gouvfr.po
Labels: in progress

#252 Align cards style (alt)
  CHANGELOG.md
  theme/less/gouvfr-dataset.less
  theme/less/gouvfr-home.less
  theme/less/gouvfr-topic.less
  theme/less/gouvfr.less
  theme/less/gouvfr/community.less
  theme/less/gouvfr/navbars.less
  theme/less/gouvfr/resources.less
  udata_gouvfr/theme/templates/home.html
Labels: in progress

#267 Discourse timeout and response parse error catch
  CHANGELOG.md
  udata_gouvfr/tests.py
  udata_gouvfr/theme/__init__.py
Labels: in progress

#270 Fix test config
  .circleci/config.yml
  udata_gouvfr/tests.py
Labels: bug, current-sprint, in progress

#268 Tracking of carousel efficiency
  CHANGELOG.md
  udata_gouvfr/theme/templates/home.html
Labels: current-sprint, in progress

#271 Add tracking on CTA
  CHANGELOG.md
  udata_gouvfr/theme/templates/subnav-large.html
Labels: in progress

#272 Remove useless style and adapt new reuse add card
  CHANGELOG.md
  theme/less/gouvfr-admin.less
  theme/less/gouvfr.less
  theme/less/gouvfr/cards.less
  theme/less/gouvfr/community.less
  theme/less/gouvfr/resources.less
  theme/less/gouvfr/variables.less
Labels: current-sprint, enhancement, in progress, user-interface
