Repository etalab/udata-gouvfr, pull requests merged in 2018-04, with the labels that each got.

#265 Typed resources related styles
  CHANGELOG.md
  theme/less/gouvfr-dataset.less
Labels: in progress

#292 Enforce a domain whitelist when resource.filetype is file (migration)
  CHANGELOG.md
  udata_gouvfr/migrations/2018-04-09-normalize-resource-filetype.js
Labels: current-sprint, in progress

#289 Resource cards
  theme/less/gouvfr/cards.less
  theme/less/gouvfr/community.less
  theme/less/gouvfr/resources.less
  theme/less/gouvfr/variables.less
Labels: current-sprint, in progress

#295 Prepare for legacy PyPI closure and PyPI warehouse supporting markdown
  .circleci/config.yml
  CHANGELOG.md
  setup.py
  tasks.py
  udata_gouvfr/theme/templates/footer.html
Labels: current-sprint, enhancement, in progress

#298 Ensure active users have a confirmed_at date
  .gitignore
  CHANGELOG.md
  udata_gouvfr/migrations/2018-04-18-migrate-active-users.js
Labels: in progress
