Repository etalab/udata-gouvfr, pull requests merged in 2018-03, with the labels that each got.

#273 Move search results fixes to upstream
  .circleci/config.yml
  theme/less/gouvfr.less
Labels: current-sprint, in progress

#274 temporary carousel layout
  CHANGELOG.md
  udata_gouvfr/theme/templates/carousel.html
  udata_gouvfr/theme/templates/home.html
Labels: in progress

#275 Fix line clamping
  theme/less/gouvfr.less
  theme/less/gouvfr/mixins.less
Labels: bug, current-sprint, in progress, user-interface

#277 tracking of dataset recommendations
  CHANGELOG.md
  theme/js/dataset-recommendations.js
  udata_gouvfr/theme/templates/dataset/display.html
Labels: in progress

#281 Fixes some cards positionning
  .circleci/config.yml
  CHANGELOG.md
  udata_gouvfr/templates/c3.html
  udata_gouvfr/templates/dataconnexions-5.html
  udata_gouvfr/templates/dataconnexions-6.html
  udata_gouvfr/templates/nec_mergitur.html
  udata_gouvfr/templates/openfield16.html
  udata_gouvfr/templates/spd.html
  udata_gouvfr/theme/templates/home.html
Labels: bug, current-sprint, in progress

#283 fix redevance page layout
  udata_gouvfr/templates/redevances.html
Labels: in progress

#284 Limit number of topics on forum integration
  CHANGELOG.md
  udata_gouvfr/theme/__init__.py
  udata_gouvfr/theme/templates/forum.html
  udata_gouvfr/theme/templates/home.html
Labels: in progress

#285 Switch to new OEmbed
  CHANGELOG.md
  theme/js/dataset-recommendations.js
  theme/less/gouvfr-dataset-recommendations.less
  theme/less/oembed.less
  theme/oembed.js
  udata_gouvfr/theme/templates/dataset/display.html
  udata_gouvfr/theme/templates/oembed.html
  webpack.config.js
Labels: current-sprint, enhancement, in progress, refactoring, user-interface

#287 Fix the RSS popover not being clickable
  CHANGELOG.md
  udata_gouvfr/theme/templates/footer.html
Labels: bug, current-sprint, in progress

#288 Drop non-certified style
  CHANGELOG.md
  theme/less/gouvfr-dataset.less
Labels: current-sprint, in progress, user-interface
